version: "3.9"

services:
  app:
    build: .
    command: bash start.sh
    restart: on-failure
    ports:
      - "3427:80"
      - "8324:8080"
      - "4344:8090"

networks:
  default:
    external: true
    name: network1
