version: "3.9"

services:
  app:
    build: .
    command: bash start.sh
    restart: on-failure
    ports:
      - "256:256"
      - "4928:4928"

networks:
  default:
    external: true
    name: network1
